export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SECCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SECCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
}

export const productConstants = {
    GET_PRODUCTS_BY_SLUG: 'GET_PRODUCTS_BY_SLUG',
    GET_PRODUCTS_PAGE_REQUEST: 'GET_PRODUCTS_PAGE_REQUEST',
    GET_PRODUCTS_PAGE_SUCCESS: 'GET_PRODUCTS_PAGE_SUCCESS',
    GET_PRODUCTS_PAGE_FAILURE: 'GET_PRODUCTS_PAGE_FAILURE',

    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE',
 



}

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILTURE: 'LOGIN_FAILURE',
    LOGIN_SECCESS: 'LOGIN_SECCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SECCESS: 'LOGOUT_SECCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}
